# Generated by Django 3.1.3 on 2021-01-17 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_profile_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='UserFollowing',
        ),
    ]
